import { Geist, Geist_Mono } from "next/font/google";
import "../styles/index.css";
import { cookies } from "next/headers";
import { getLocale } from "next-intl/server";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // ✅ Locale from next-intl (works at root with the v4 plugin)
  const locale = await getLocale();
  console.log("Current locale Root:", locale);

  // ✅ Initial theme from cookie (keep SSR/CSR in sync)
  const store = await cookies();
  const initialTheme = store.get("theme")?.value === "dark" ? "dark" : "light";

  return (
    <html lang={locale} className={initialTheme} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
